language: cpp
notifications:
  email: false

matrix:
  include:

  - name: "Linux gcc"
    os: linux
    dist: bionic
    compiler: gcc
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libgl1-mesa-dev
            - x11proto-core-dev
            - libx11-dev
    script:
        - export CXX="g++-8" CC="gcc-8"
        - mkdir build && cd build
        - cmake ..
        - make

  - name: "Linux clang"
    os: linux
    dist: bionic
    compiler: clang
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - cmake
            - libgl1-mesa-dev
            - x11proto-core-dev
            - libx11-dev
    script:
        - export CXX="clang" CC="clang"
        - mkdir build && cd build
        - cmake ..
        - make

  - name: "macOS Xcode 12"
    os: osx
    osx_image: xcode12
    addons:
        apt:
          packages:
            - clang
            - cmake
            - libgl1-mesa-dev
            - x11proto-core-dev
            - libx11-dev
    script:
        - mkdir build && cd build
        - cmake ..
        - make
    
#  - name: "Visual studio 17 2019"
#    os: windows
#    addons:
#        apt:
#          packages:
#            - cmake
#            - libxrandr-dev
#            - libudev-dev
#            - libopenal-dev
#            - libflac-dev
#            - libvorbis-dev
#            - libgl1-mesa-dev
#    script:
#        - mkdir build && cd build
#        - cmake ..
#        - make